version: '3.8'

services:
  backend:
    build: ./backend
    container_name: scriptify-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: 
       context: "./frontend text converter"
       dockerfile: Dockerfile
    container_name: scriptify-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
