apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Base64 encoded API keys - Replace these with your actual encoded keys
  # To encode: echo -n "your-api-key" | base64
  gemini-api-key: "UExBQ0VIT0xERVJfR0VNSU5JX0tFWQ==" # Replace with your actual base64 encoded Gemini API key
  assemblyai-api-key: "ZmQ0NTM2YzUyZTc4NGEyNzkwNGQxOTdlOTY1OTA2Y2Y=" # Your AssemblyAI API key (already encoded)
