apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Base64 encoded API keys - you need to replace these with your actual encoded keys
  # To encode: echo -n "your-api-key" | base64
  gemini-api-key: "eW91ci1nZW1pbmktYXBpLWtleQ==" # Replace with your actual base64 encoded Gemini API key
  assemblyai-api-key: "ZmQ0NTM2YzUyZTc4NGEyNzkwNGQxOTdlOTY1OTA2Y2Y=" # Replace with your actual base64 encoded AssemblyAI API key
