name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        run: |
          docker build -t ayushchoudhary6/scriptify-backend:latest ./backend
          docker push ayushchoudhary6/scriptify-backend:latest

      - name: Build & Push Frontend Image
        run: |
          docker build -t ayushchoudhary6/scriptify-frontend:latest ./frontend
          docker push ayushchoudhary6/scriptify-frontend:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            k8s/backend-deployment.yml
            k8s/frontend-deployment.yml
            k8s/backend-service.yml
            k8s/frontend-service.yml
            k8s/ingress.yml
            k8s/hpa.yml
          namespace: default

      - name: Get App URL
        run: |
          echo "App deployed successfully!"
          echo "Access via: kubectl port-forward -n ingress-nginx svc/ingress-nginx-controller 8080:80"
          echo "Then visit: http://localhost:8080"
