name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE_BACKEND: ayushchoudhary6/scriptify-backend:latest
  DOCKER_IMAGE_FRONTEND: ayushchoudhary6/scriptify-frontend:latest

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Backend Image
      run: |
        echo "=== Building Backend Image ==="
        docker build -t $DOCKER_IMAGE_BACKEND ./backend
        
    - name: Push Backend Image
      run: |
        echo "=== Pushing Backend Image ==="
        docker push $DOCKER_IMAGE_BACKEND

  build-frontend:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Frontend Image
      run: |
        echo "=== Building Frontend Image ==="
        docker build -t $DOCKER_IMAGE_FRONTEND ./frontend
        
    - name: Push Frontend Image
      run: |
        echo "=== Pushing Frontend Image ==="
        docker push $DOCKER_IMAGE_FRONTEND

  deploy:
    needs: [build-backend, build-frontend]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Kubernetes
      run: |
        echo "=== Deploying to Kubernetes ==="
        kubectl apply -f k8s/
        kubectl rollout restart deployment/backend-deployment
        kubectl rollout restart deployment/frontend-deployment
        kubectl rollout status deployment/backend-deployment
        kubectl rollout status deployment/frontend-deployment
        echo "=== Deployment Complete ==="
        kubectl get ingress
